export enum CourseAction {
    ADD_COURSE = 'ADD_COURSE',
    EDIT_COURSE = 'EDIT_COURSE',
    DELETE_COURSE = 'DELETE_COURSE',
    GET_ALL_COURSES = 'GET_ALL_COURSES',
    FIND_COURSES = 'FIND_COURSES'
}
